#ifndef KEYWORDS_H
#define KEYWORDS_H
#define CHR_CODE(a,b,c,d) (a + (b<<7) + (c<<14) + (d<<21)) % 207

#define LPAREN CHR_CODE('(',0,0,0)
#define RPAREN CHR_CODE(')',0,0,0)
#define TRUE CHR_CODE('t','r','u','e')
#define FALSE CHR_CODE('f','a','l','s')
#define NIL CHR_CODE('n','i','l',0)
#define IF CHR_CODE('i','f',0,0)
#define ELSE CHR_CODE('e','l','s','e')
#define WHILE CHR_CODE('w','h','i','l')
#define DEF CHR_CODE('d','e','f',0)
#define RET CHR_CODE('r','e','t',0)
#define ARGS CHR_CODE('a','r','g','s')
#define CALL CHR_CODE('c','a','l','l')
#define ASSIGN CHR_CODE('=',0,0,0)
#define EQUALS CHR_CODE('=','=',0,0)
#define LESS CHR_CODE('<',0,0,0)
#define GREATER CHR_CODE('>',0,0,0)
#define LESSEQ CHR_CODE('<','=',0,0)
#define GREATEREQ CHR_CODE('>','=',0,0)
#define AND CHR_CODE('&',0,0,0)
#define OR CHR_CODE('|',0,0,0)
#define NOT CHR_CODE('~',0,0,0)
#define NEGATE CHR_CODE('!',0,0,0)
#define PLUS CHR_CODE('+',0,0,0)
#define INC CHR_CODE('+','+',0,0)
#define MINUS CHR_CODE('-',0,0,0)
#define DEC CHR_CODE('-','-',0,0)
#define LSHIFT CHR_CODE('<','<',0,0)
#define RSHIFT CHR_CODE('>','>',0,0)
#define TIMES CHR_CODE('*',0,0,0)
#define DIVIDE CHR_CODE('/',0,0,0)
#define SSTART CHR_CODE('s','s','t','a')
#define SWRITE CHR_CODE('s','w','r','i')
#define SREAD CHR_CODE('s','r','e','a')
#define GPMODE CHR_CODE('g','p','m','o')
#define GPSET CHR_CODE('g','p','s','e')
#define GPREAD CHR_CODE('g','p','r','e')
#define SLEEP CHR_CODE('s','l','e','e')
#define ID CHR_CODE('i','d',0,0)
#define STRLIT CHR_CODE('s','t','r','l')
#define INT CHR_CODE('i','n','t',0)
#define FLOAT CHR_CODE('f','l','o','a')
#endif /* KEYWORDS_H */
